### ISSUE TITLE
"Module Parse Failed: ... package.json Unexpected token"

### ISSUE THREAD

**Issue by danab** [softonic/axios-retry#15]
I noticed today that my build was failing, and throwing this error.

```
ERROR in ./~/axios-retry/package.json
Module parse failed: /source/node_modules/axios-retry/package.json Unexpected token (2:9)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (2:9)
at Parser.pp$4.raise (/source/node_modules/webpack/node_modules/acorn/dist/acorn.js:2221:15)
at Parser.pp.unexpected (/source/node_modules/webpack/node_modules/acorn/dist/acorn.js:603:10)
at Parser.pp.semicolon (/source/node_modules/webpack/node_modules/acorn/dist/acorn.js:581:61)
at Parser.pp$1.parseExpressionStatement (/source/node_modules/webpack/node_modules/acorn/dist/acorn.js:966:10)
at Parser.pp$1.parseStatement (/source/node_modules/webpack/node_modules/acorn/dist/acorn.js:730:24)
at Parser.pp$1.parseBlock (/source/node_modules/webpack/node_modules/acorn/dist/acorn.js:981:25)
at Parser.pp$1.parseStatement (/source/node_modules/webpack/node_modules/acorn/dist/acorn.js:709:33)
at Parser.pp$1.parseTopLevel (/source/node_modules/webpack/node_modules/acorn/dist/acorn.js:638:25)
at Parser.parse (/source/node_modules/webpack/node_modules/acorn/dist/acorn.js:516:17)
at Object.parse (/source/node_modules/webpack/node_modules/acorn/dist/acorn.js:3098:39)
at Parser.parse (/source/node_modules/webpack/lib/Parser.js:902:15)
at DependenciesBlock.<anonymous> (/source/node_modules/webpack/lib/NormalModule.js:104:16)
at DependenciesBlock.onModuleBuild (/source/node_modules/webpack-core/lib/NormalModuleMixin.js:310:10)
at nextLoader (/source/node_modules/webpack-core/lib/NormalModuleMixin.js:275:25)
at /source/node_modules/webpack-core/lib/NormalModuleMixin.js:259:5
at Storage.provide (/source/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:52:20)
at CachedInputFileSystem.readFile (/source/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:140:24)
at DependenciesBlock.onLoadPitchDone (/source/node_modules/webpack-core/lib/NormalModuleMixin.js:255:7)
at DependenciesBlock.loadPitch (/source/node_modules/webpack-core/lib/NormalModuleMixin.js:182:27)
at DependenciesBlock.doBuild (/source/node_modules/webpack-core/lib/NormalModuleMixin.js:241:4)
at DependenciesBlock.build (/source/node_modules/webpack/lib/NormalModule.js:84:14)
at Compilation.buildModule (/source/node_modules/webpack/lib/Compilation.js:126:9)
at /source/node_modules/webpack/lib/Compilation.js:309:10
at /source/node_modules/webpack/lib/NormalModuleFactory.js:58:13
at NormalModuleFactory.applyPluginsAsyncWaterfall (/source/node_modules/tapable/lib/Tapable.js:75:69)
at onDoneResolving (/source/node_modules/webpack/lib/NormalModuleFactory.js:38:11)
at onDoneResolving (/source/node_modules/webpack/lib/NormalModuleFactory.js:121:6)
at /source/node_modules/webpack/lib/NormalModuleFactory.js:116:7
at /source/node_modules/webpack/node_modules/async/lib/async.js:726:13
at /source/node_modules/webpack/node_modules/async/lib/async.js:52:16
@ ./~/axios-retry/lib/index.js 13:15-41
```

My package.json included:

```
{
  "dependencies": {
    "axios-retry": "^1.1.0"
  }
}
```

Tried upgrading to 2.0. Same error. Tied it directly to 1.1.0 (removed the `^`) and it seemed to work. Sorry I'm unclear about what is actually going on, or I would just send a PR. Hope that's helpful and thank you for the package.

**Comment by rubennorte** [comment]
Fixed both in v1 (1.3.1) and in v2 (2.0.1). We were importing the `package.json` file just to get the package name to namespace values in axios request configurations. We just hardcoded it so the import is not necessary.
