### ISSUE TITLE
Failed to execute 'setRequestHeader' on 'XMLHttpRequest' 

### ISSUE THREAD

**Issue by m-swat** [softonic/axios-retry#217]
Hi, 
i'm getting error like 'Failed to execute 'setRequestHeader' on 'XMLHttpRequest'' on 5xx error when retrying should occur.

`SyntaxError:Failed to execute 'setRequestHeader' on 'XMLHttpRequest': 'function(header, parser) {
    header = normalizeHeader(header);

    if (!header) return undefined;

    const key = findKey(this, header);

    if (key) {
      const value = this[key];

      if (!parser) {
        return value;
      }

      if (parser === true) {
        return parseTokens(value);
      }

      if (_utils_js__WEBPACK_IMPORTED_MODULE_0__["default"].isFunction(parser)) {
        return parser.call(this, value, key);
      }

      if (_utils_js__WEBPACK_IMPORTED_MODULE_0__["default"].isRegExp(parser)) {
        return parser.exec(value);
      }

      throw new TypeError('parser must be boolean|regexp|function');
    }
  }' is not a valid HTTP header field value.`
Here is a full Error message:

It looks like the whole function definition is passed as a header value :o

I'm using the newest Axios version(1.1.3) and the newest retry-axios. No idea what is wrong. The same code is working fine with Axios 0.27.x.

Any idea what could be wrong?

**Comment by m-swat** [comment]
As I see, a similar problem occurs in node environment, not only in the browser(problem with setting header):

`[ERR_INVALID_CHAR]: Invalid character in header content ["0"]
    at ClientRequest.setHeader (_http_outgoing.js:564:3)
    at new ClientRequest (_http_client.js:262:14)
    at Object.request (https.js:370:10)
    at RedirectableRequest._performRequest (/home/mswat/workspace/test-axios/node_modules/follow-redirects/index.js:284:24)
    at new RedirectableRequest (/home/mswat/workspace/test-axios/node_modules/follow-redirects/index.js:66:8)
    at Object.request (/home/mswat/workspace/test-axios/node_modules/follow-redirects/index.js:523:14)
    at dispatchHttpRequest (file:///home/mswat/workspace/test-axios/node_modules/axios/lib/adapters/http.js:371:21)
    at new Promise (<anonymous>)
    at httpAdapter (file:///home/mswat/workspace/test-axios/node_modules/axios/lib/adapters/http.js:105:10)
    at Axios.dispatchRequest (file:///home/mswat/workspace/test-axios/node_modules/axios/lib/core/dispatchRequest.js:46:10) {
  code: 'ERR_INVALID_CHAR',
  config: {
    raxConfig: {
      currentRetryAttempt: 0,
      retry: 3,
      retryDelay: 100,
      instance: [Function],
      backoffType: 'exponential',
      httpMethodsToRetry: [Array],
      noResponseRetries: 2,
      checkRetryAfter: true,
      maxRetryAfter: 300000,
      statusCodesToRetry: [Array]
    }
  }
}
(node:6354) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_CHAR]: Invalid character in header content ["0"]
    at ClientRequest.setHeader (_http_outgoing.js:564:3)
    at new ClientRequest (_http_client.js:262:14)
    at Object.request (https.js:370:10)
    at RedirectableRequest._performRequest (/home/mswat/workspace/test-axios/node_modules/follow-redirects/index.js:284:24)
    at new RedirectableRequest (/home/mswat/workspace/test-axios/node_modules/follow-redirects/index.js:66:8)
    at Object.request (/home/mswat/workspace/test-axios/node_modules/follow-redirects/index.js:523:14)
    at dispatchHttpRequest (file:///home/mswat/workspace/test-axios/node_modules/axios/lib/adapters/http.js:371:21)
    at new Promise (<anonymous>)
    at httpAdapter (file:///home/mswat/workspace/test-axios/node_modules/axios/lib/adapters/http.js:105:10)
    at Axios.dispatchRequest (file:///home/mswat/workspace/test-axios/node_modules/axios/lib/core/dispatchRequest.js:46:10)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:6354) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 5)
(node:6354) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

Node: v14
axios: v1.1.3
axios-retry: v3.3.1

**Comment by m-swat** [comment]
issue related to: https://github.com/axios/axios/issues/5089
