### ISSUE TITLE
429 error isn't caught by axios-retry

### ISSUE THREAD

**Issue by garyking** [softonic/axios-retry#51]
Is this a bug? I'm using axios to read some URLs. Sometimes I get a `429 TOO MANY REQUESTS` error. Therefore I have code like the following:

```javascript
      const retryCondition = (error) => {
        return (
          axiosRetry.isNetworkOrIdempotentRequestError(error) ||
          error.response.status === 429
        );
      };

      axiosRetry(axios, {
        retryDelay: axiosRetry.exponentialDelay,
        retryCondition,
      });

      const response = await axios.get(url);
      return response.data;
```

Yet I still get tons of errors like this:

```
(node:77568) UnhandledPromiseRejectionWarning: Error: Request failed with status code 429
    at createError (/Users/gary/Downloads/Unsorted/code/web-scraper/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/Users/gary/Downloads/Unsorted/code/web-scraper/node_modules/axios/lib/core/settle.js:18:12)
    at IncomingMessage.handleStreamEnd (/Users/gary/Downloads/Unsorted/code/web-scraper/node_modules/axios/lib/adapters/http.js:201:11)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
(node:77568) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 45852)
```

Isn't the code I have supposed to catch all 429 errors, so these errors shouldn't appear in the terminal? 

I notice that most 429 errors are actually caught, but some are not. And those ones result in the error above. Perhaps they don't get caught when there are too many or something?

**Comment by garyking** [comment]
I'm an idiot. `retries` is set to `3` by default. I just need to set it to a higher number.
